name: graphql
description: GitHub Action GraphQL Checks
inputs:
  service:
    description: name of the service in graphql
    required: true

  endpoint:
    description: endpoint where graphql schema can be retrieved
    required: true

  key:
    description: apollo key
    required: true

  token:
    description: github token with read privileges
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: rabotaua/mavis
        ref: main
        token: ${{ inputs.token }}
        path: .github/mavis

    - name: npm install
      shell: bash
      working-directory: .github/mavis
      run: npm install > /dev/null

    - name: mavis
      shell: bash
      working-directory: .github/mavis
      run: node cli.js ${{ inputs.endpoint }} ${{ inputs.service }}
      #env:
      #  APOLLO_KEY: ${{ inputs.key }}

    # - name: apollo
    #   shell: bash
    #   working-directory: .github/mavis
    #   run: npx apollo service:check --serviceName=${{ inputs.service }} --graph=dracula --key=${{ inputs.key }} --endpoint=${{ inputs.endpoint }}
    - name: rover
      shell: bash
      env:
        APOLLO_KEY: ${{ inputs.key }}
      run: |
        curl -sSL https://rover.apollo.dev/nix/v0.22.0 | sh
        /home/runner/.rover/bin/rover subgraph introspect ${{ inputs.endpoint }} | rover subgraph check 'dracula@current' --name ${{ inputs.service }} --schema -
